[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "/api"

# Redirection des appels API vers le backend
[[redirects]]
  from = "/api/*"
  to = "https://api.harmonith.fr/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Copier _headers depuis public vers dist
[[plugins]]
  package = "@netlify/plugin-local-install-core"
